import Head from "next/head";
import axios from "axios";
import crypto from "crypto";
import Layout from "../../components/layout";
import { Grid } from "@mui/material";
import CharacterDetails from "../../components/CharacterDetails/CharacterDetails";

function transformCharacterData(character) {
  return {
    id: character.id,
    name: character.name,
    description: character.description,
    image: character.thumbnail,
  };
}

export default function CharacterDetailPage(props) {
  const { character } = props;
  return (
    <>
      <Head>
        <title>Marvel Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Grid container spacing={4} style={{ padding: "2rem 0" }}>
          <CharacterDetails character={character} />
        </Grid>
      </Layout>
    </>
  );
}

export async function getServerSideProps(context) {
  const timespan = new Date().toString();
  const { characterId } = context.params;

  const privateKey = process.env.marvelAPI.privateKey;
  const publicKey = process.env.marvelAPI.publicKey;
  const hash = crypto
    .createHash("md5")
    .update(timespan + privateKey + publicKey)
    .digest("hex");

  const response = await axios.get(
    `https://gateway.marvel.com/v1/public/characters/${characterId}`,
    {
      params: {
        hash,
        ts: timespan,
        apikey: publicKey,
      },
    }
  );

  const characterData = response.data.data.results;
  const character = characterData[0];

  return {
    props: {
      character: transformCharacterData(character),
    },
  };
}
