import Head from 'next/head'
import axios from 'axios';
import crypto from 'crypto';
import styles from '../styles/Home.module.css'
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';

export default function HomePage(props) {
  console.log('Homepage', props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack spacing={2} direction="row">
        <Button variant="text">Text</Button>
        <Button variant="contained">Contained</Button>
        <Button variant="outlined">Outlined</Button>
      </Stack>
    </div>
  )
}

export async function getStaticProps(context) {
  const timespan = new Date().toString();

  const privateKey = "0ebdc1da819a0545afbbfe3f7837e367c8792a51";
  const publicKey = "2665bc66e2c6b9a710725eea2dc6710a";
  const hash = crypto.createHash('md5').update(timespan + privateKey + publicKey).digest('hex');

  const response = await axios.get('https://gateway.marvel.com/v1/public/characters', {
    params: {
      hash,
      ts: timespan,
      apikey: '2665bc66e2c6b9a710725eea2dc6710a',
    }
  });

  const charactersData = response.data.data.results;

  return {
    props: {
      characters: charactersData
    }
  }
}